### ISSUE TITLE
Keyboard notifications

### ISSUE THREAD

**Issue by stansey** [jeffh/Robot#3]
Should keyboard notifications fire when a UITextField is focused? We wanted to test that we move our scroll view when a text field is tapped and gets covered by the keyboard. We found that the UIKeyboardWillShowNotification seems not to fire.

Is this a desirable feature?

**Comment by jeffh** [comment]
Yeah, this is desirable to have for keyboard handling.

**Comment by jeffh** [comment]
This is now fixed for iOS 8+
